// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: clips_facts.proto
// Original file comments:
// Protobuf3.0
// @description Definition of the CLIPS6.30 facts format
// @author Zhaozihe
// @date 2018-7-16 11:32:57
//
#ifndef GRPC_clips_5ffacts_2eproto__INCLUDED
#define GRPC_clips_5ffacts_2eproto__INCLUDED

#include "clips_facts.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace buaa {
namespace facts {

}  // namespace facts
}  // namespace buaa


#endif  // GRPC_clips_5ffacts_2eproto__INCLUDED
