// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dss.proto

#include "dss.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace buaa {
namespace dss {
class placeholderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<placeholder>
      _instance;
} _placeholder_default_instance_;
}  // namespace dss
}  // namespace buaa
namespace protobuf_dss_2eproto {
void InitDefaultsplaceholderImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::buaa::dss::_placeholder_default_instance_;
    new (ptr) ::buaa::dss::placeholder();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::buaa::dss::placeholder::InitAsDefaultInstance();
}

void InitDefaultsplaceholder() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsplaceholderImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::buaa::dss::placeholder, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::buaa::dss::placeholder)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::buaa::dss::_placeholder_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "dss.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tdss.proto\022\010buaa.dss\032\021clips_facts.proto"
      "\032\nfile.proto\"\r\n\013placeholder2\356\005\n\tReasonin"
      "g\022A\n\022GetReasoningResult\022\025.buaa.dss.place"
      "holder\032\022.buaa.facts.result\"\000\022@\n\016StartRea"
      "soning\022\025.buaa.facts.sim_start\032\025.buaa.dss"
      ".placeholder\"\000\022C\n\013GetRuleFile\022\025.buaa.dss"
      ".placeholder\032\031.buaa.file.rule_file_info\""
      "\0000\001\022C\n\014LoadRuleFile\022\030.buaa.file.rule_fil"
      "e_chk\032\025.buaa.dss.placeholder\"\000(\001\022\?\n\014GetF"
      "actSlots\022\025.buaa.dss.placeholder\032\024.buaa.f"
      "ile.fact_list\"\0000\001\022\?\n\014SetFactSlots\022\024.buaa"
      ".file.fact_list\032\025.buaa.dss.placeholder\"\000"
      "(\001\022C\n\013GetFactFile\022\025.buaa.dss.placeholder"
      "\032\031.buaa.file.fact_file_info\"\0000\001\022C\n\014LoadF"
      "actFile\022\030.buaa.file.fact_file_chk\032\025.buaa"
      ".dss.placeholder\"\000(\001\022C\n\020GetSelectedSlots"
      "\022\025.buaa.dss.placeholder\032\024.buaa.file.fact"
      "_list\"\0000\001\022A\n\017GetVariableList\022\025.buaa.dss."
      "placeholder\032\023.buaa.file.fact_var\"\0000\001\022>\n\016"
      "SetMappingList\022\021.buaa.file.mapper\032\025.buaa"
      ".dss.placeholder\"\000(\001P\000P\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 832);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dss.proto", &protobuf_RegisterTypes);
  ::protobuf_clips_5ffacts_2eproto::AddDescriptors();
  ::protobuf_file_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_dss_2eproto
namespace buaa {
namespace dss {

// ===================================================================

void placeholder::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

placeholder::placeholder()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_dss_2eproto::InitDefaultsplaceholder();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:buaa.dss.placeholder)
}
placeholder::placeholder(const placeholder& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:buaa.dss.placeholder)
}

void placeholder::SharedCtor() {
  _cached_size_ = 0;
}

placeholder::~placeholder() {
  // @@protoc_insertion_point(destructor:buaa.dss.placeholder)
  SharedDtor();
}

void placeholder::SharedDtor() {
}

void placeholder::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* placeholder::descriptor() {
  ::protobuf_dss_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dss_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const placeholder& placeholder::default_instance() {
  ::protobuf_dss_2eproto::InitDefaultsplaceholder();
  return *internal_default_instance();
}

placeholder* placeholder::New(::google::protobuf::Arena* arena) const {
  placeholder* n = new placeholder;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void placeholder::Clear() {
// @@protoc_insertion_point(message_clear_start:buaa.dss.placeholder)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool placeholder::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:buaa.dss.placeholder)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:buaa.dss.placeholder)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:buaa.dss.placeholder)
  return false;
#undef DO_
}

void placeholder::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:buaa.dss.placeholder)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:buaa.dss.placeholder)
}

::google::protobuf::uint8* placeholder::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:buaa.dss.placeholder)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:buaa.dss.placeholder)
  return target;
}

size_t placeholder::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:buaa.dss.placeholder)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void placeholder::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:buaa.dss.placeholder)
  GOOGLE_DCHECK_NE(&from, this);
  const placeholder* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const placeholder>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:buaa.dss.placeholder)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:buaa.dss.placeholder)
    MergeFrom(*source);
  }
}

void placeholder::MergeFrom(const placeholder& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:buaa.dss.placeholder)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void placeholder::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:buaa.dss.placeholder)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void placeholder::CopyFrom(const placeholder& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:buaa.dss.placeholder)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool placeholder::IsInitialized() const {
  return true;
}

void placeholder::Swap(placeholder* other) {
  if (other == this) return;
  InternalSwap(other);
}
void placeholder::InternalSwap(placeholder* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata placeholder::GetMetadata() const {
  protobuf_dss_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_dss_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace dss
}  // namespace buaa

// @@protoc_insertion_point(global_scope)
