// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dss.proto

#ifndef PROTOBUF_dss_2eproto__INCLUDED
#define PROTOBUF_dss_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "clips_facts.pb.h"  // IWYU pragma: export
#include "file.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protobuf_dss_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsplaceholderImpl();
void InitDefaultsplaceholder();
inline void InitDefaults() {
  InitDefaultsplaceholder();
}
}  // namespace protobuf_dss_2eproto
namespace buaa {
namespace dss {
class placeholder;
class placeholderDefaultTypeInternal;
extern placeholderDefaultTypeInternal _placeholder_default_instance_;
}  // namespace dss
}  // namespace buaa
namespace buaa {
namespace dss {

// ===================================================================

class placeholder : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:buaa.dss.placeholder) */ {
 public:
  placeholder();
  virtual ~placeholder();

  placeholder(const placeholder& from);

  inline placeholder& operator=(const placeholder& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  placeholder(placeholder&& from) noexcept
    : placeholder() {
    *this = ::std::move(from);
  }

  inline placeholder& operator=(placeholder&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const placeholder& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const placeholder* internal_default_instance() {
    return reinterpret_cast<const placeholder*>(
               &_placeholder_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(placeholder* other);
  friend void swap(placeholder& a, placeholder& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline placeholder* New() const PROTOBUF_FINAL { return New(NULL); }

  placeholder* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const placeholder& from);
  void MergeFrom(const placeholder& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(placeholder* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:buaa.dss.placeholder)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_dss_2eproto::TableStruct;
  friend void ::protobuf_dss_2eproto::InitDefaultsplaceholderImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// placeholder

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace dss
}  // namespace buaa

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dss_2eproto__INCLUDED
