# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dss.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import clips_facts_pb2 as clips__facts__pb2
try:
  flight__control__pb2 = clips__facts__pb2.flight__control__pb2
except AttributeError:
  flight__control__pb2 = clips__facts__pb2.flight_control_pb2
try:
  comm__link__pb2 = clips__facts__pb2.comm__link__pb2
except AttributeError:
  comm__link__pb2 = clips__facts__pb2.comm_link_pb2
import file_pb2 as file__pb2

from clips_facts_pb2 import *
from file_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='dss.proto',
  package='buaa.dss',
  syntax='proto3',
  serialized_pb=_b('\n\tdss.proto\x12\x08\x62uaa.dss\x1a\x11\x63lips_facts.proto\x1a\nfile.proto\"\r\n\x0bplaceholder2\xee\x05\n\tReasoning\x12\x41\n\x12GetReasoningResult\x12\x15.buaa.dss.placeholder\x1a\x12.buaa.facts.result\"\x00\x12@\n\x0eStartReasoning\x12\x15.buaa.facts.sim_start\x1a\x15.buaa.dss.placeholder\"\x00\x12\x43\n\x0bGetRuleFile\x12\x15.buaa.dss.placeholder\x1a\x19.buaa.file.rule_file_info\"\x00\x30\x01\x12\x43\n\x0cLoadRuleFile\x12\x18.buaa.file.rule_file_chk\x1a\x15.buaa.dss.placeholder\"\x00(\x01\x12?\n\x0cGetFactSlots\x12\x15.buaa.dss.placeholder\x1a\x14.buaa.file.fact_list\"\x00\x30\x01\x12?\n\x0cSetFactSlots\x12\x14.buaa.file.fact_list\x1a\x15.buaa.dss.placeholder\"\x00(\x01\x12\x43\n\x0bGetFactFile\x12\x15.buaa.dss.placeholder\x1a\x19.buaa.file.fact_file_info\"\x00\x30\x01\x12\x43\n\x0cLoadFactFile\x12\x18.buaa.file.fact_file_chk\x1a\x15.buaa.dss.placeholder\"\x00(\x01\x12\x43\n\x10GetSelectedSlots\x12\x15.buaa.dss.placeholder\x1a\x14.buaa.file.fact_list\"\x00\x30\x01\x12\x41\n\x0fGetVariableList\x12\x15.buaa.dss.placeholder\x1a\x13.buaa.file.fact_var\"\x00\x30\x01\x12>\n\x0eSetMappingList\x12\x11.buaa.file.mapper\x1a\x15.buaa.dss.placeholder\"\x00(\x01P\x00P\x01\x62\x06proto3')
  ,
  dependencies=[clips__facts__pb2.DESCRIPTOR,file__pb2.DESCRIPTOR,],
  public_dependencies=[clips__facts__pb2.DESCRIPTOR,file__pb2.DESCRIPTOR,])




_PLACEHOLDER = _descriptor.Descriptor(
  name='placeholder',
  full_name='buaa.dss.placeholder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['placeholder'] = _PLACEHOLDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

placeholder = _reflection.GeneratedProtocolMessageType('placeholder', (_message.Message,), dict(
  DESCRIPTOR = _PLACEHOLDER,
  __module__ = 'dss_pb2'
  # @@protoc_insertion_point(class_scope:buaa.dss.placeholder)
  ))
_sym_db.RegisterMessage(placeholder)



_REASONING = _descriptor.ServiceDescriptor(
  name='Reasoning',
  full_name='buaa.dss.Reasoning',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=70,
  serialized_end=820,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetReasoningResult',
    full_name='buaa.dss.Reasoning.GetReasoningResult',
    index=0,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=clips__facts__pb2._RESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartReasoning',
    full_name='buaa.dss.Reasoning.StartReasoning',
    index=1,
    containing_service=None,
    input_type=clips__facts__pb2._SIM_START,
    output_type=_PLACEHOLDER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRuleFile',
    full_name='buaa.dss.Reasoning.GetRuleFile',
    index=2,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=file__pb2._RULE_FILE_INFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadRuleFile',
    full_name='buaa.dss.Reasoning.LoadRuleFile',
    index=3,
    containing_service=None,
    input_type=file__pb2._RULE_FILE_CHK,
    output_type=_PLACEHOLDER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFactSlots',
    full_name='buaa.dss.Reasoning.GetFactSlots',
    index=4,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=file__pb2._FACT_LIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetFactSlots',
    full_name='buaa.dss.Reasoning.SetFactSlots',
    index=5,
    containing_service=None,
    input_type=file__pb2._FACT_LIST,
    output_type=_PLACEHOLDER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFactFile',
    full_name='buaa.dss.Reasoning.GetFactFile',
    index=6,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=file__pb2._FACT_FILE_INFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoadFactFile',
    full_name='buaa.dss.Reasoning.LoadFactFile',
    index=7,
    containing_service=None,
    input_type=file__pb2._FACT_FILE_CHK,
    output_type=_PLACEHOLDER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSelectedSlots',
    full_name='buaa.dss.Reasoning.GetSelectedSlots',
    index=8,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=file__pb2._FACT_LIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetVariableList',
    full_name='buaa.dss.Reasoning.GetVariableList',
    index=9,
    containing_service=None,
    input_type=_PLACEHOLDER,
    output_type=file__pb2._FACT_VAR,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetMappingList',
    full_name='buaa.dss.Reasoning.SetMappingList',
    index=10,
    containing_service=None,
    input_type=file__pb2._MAPPER,
    output_type=_PLACEHOLDER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REASONING)

DESCRIPTOR.services_by_name['Reasoning'] = _REASONING

# @@protoc_insertion_point(module_scope)
