# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='file.proto',
  package='buaa.file',
  syntax='proto3',
  serialized_pb=_b('\n\nfile.proto\x12\tbuaa.file\"K\n\x0erule_file_info\x12\x11\n\tfile_name\x18\x01 \x01(\x0c\x12\x11\n\tfile_desc\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63reate_time\x18\x03 \x01(\x0c\"2\n\rrule_file_chk\x12\x0f\n\x07ischeck\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\x0c\"\x1f\n\nrule_names\x12\x11\n\trule_name\x18\x01 \x01(\x0c\"\x1f\n\nfact_names\x12\x11\n\tfact_name\x18\x01 \x01(\x0c\"K\n\x0e\x66\x61\x63t_file_info\x12\x11\n\tfile_name\x18\x01 \x01(\x0c\x12\x11\n\tfile_desc\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63reate_time\x18\x03 \x01(\x0c\"2\n\rfact_file_chk\x12\x0f\n\x07ischeck\x18\x01 \x01(\x08\x12\x10\n\x08\x66ilename\x18\x02 \x01(\x0c\"5\n\tfact_list\x12\x15\n\rtemplate_name\x18\x01 \x01(\x0c\x12\x11\n\tslot_name\x18\x02 \x01(\x0c\";\n\x08\x66\x61\x63t_var\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x10\n\x08var_name\x18\x02 \x01(\x0c\x12\x0f\n\x07var_val\x18\x03 \x01(\x0c\":\n\x06mapper\x12\x10\n\x08template\x18\x01 \x01(\x0c\x12\x0c\n\x04slot\x18\x02 \x01(\x0c\x12\x10\n\x08variable\x18\x03 \x01(\x0c\x62\x06proto3')
)




_RULE_FILE_INFO = _descriptor.Descriptor(
  name='rule_file_info',
  full_name='buaa.file.rule_file_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='buaa.file.rule_file_info.file_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_desc', full_name='buaa.file.rule_file_info.file_desc', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='buaa.file.rule_file_info.create_time', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=100,
)


_RULE_FILE_CHK = _descriptor.Descriptor(
  name='rule_file_chk',
  full_name='buaa.file.rule_file_chk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ischeck', full_name='buaa.file.rule_file_chk.ischeck', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='buaa.file.rule_file_chk.filename', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=152,
)


_RULE_NAMES = _descriptor.Descriptor(
  name='rule_names',
  full_name='buaa.file.rule_names',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rule_name', full_name='buaa.file.rule_names.rule_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=185,
)


_FACT_NAMES = _descriptor.Descriptor(
  name='fact_names',
  full_name='buaa.file.fact_names',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fact_name', full_name='buaa.file.fact_names.fact_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=218,
)


_FACT_FILE_INFO = _descriptor.Descriptor(
  name='fact_file_info',
  full_name='buaa.file.fact_file_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='buaa.file.fact_file_info.file_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_desc', full_name='buaa.file.fact_file_info.file_desc', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='buaa.file.fact_file_info.create_time', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=295,
)


_FACT_FILE_CHK = _descriptor.Descriptor(
  name='fact_file_chk',
  full_name='buaa.file.fact_file_chk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ischeck', full_name='buaa.file.fact_file_chk.ischeck', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='buaa.file.fact_file_chk.filename', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=347,
)


_FACT_LIST = _descriptor.Descriptor(
  name='fact_list',
  full_name='buaa.file.fact_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template_name', full_name='buaa.file.fact_list.template_name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot_name', full_name='buaa.file.fact_list.slot_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=402,
)


_FACT_VAR = _descriptor.Descriptor(
  name='fact_var',
  full_name='buaa.file.fact_var',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='buaa.file.fact_var.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_name', full_name='buaa.file.fact_var.var_name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='var_val', full_name='buaa.file.fact_var.var_val', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=463,
)


_MAPPER = _descriptor.Descriptor(
  name='mapper',
  full_name='buaa.file.mapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='template', full_name='buaa.file.mapper.template', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot', full_name='buaa.file.mapper.slot', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variable', full_name='buaa.file.mapper.variable', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=523,
)

DESCRIPTOR.message_types_by_name['rule_file_info'] = _RULE_FILE_INFO
DESCRIPTOR.message_types_by_name['rule_file_chk'] = _RULE_FILE_CHK
DESCRIPTOR.message_types_by_name['rule_names'] = _RULE_NAMES
DESCRIPTOR.message_types_by_name['fact_names'] = _FACT_NAMES
DESCRIPTOR.message_types_by_name['fact_file_info'] = _FACT_FILE_INFO
DESCRIPTOR.message_types_by_name['fact_file_chk'] = _FACT_FILE_CHK
DESCRIPTOR.message_types_by_name['fact_list'] = _FACT_LIST
DESCRIPTOR.message_types_by_name['fact_var'] = _FACT_VAR
DESCRIPTOR.message_types_by_name['mapper'] = _MAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

rule_file_info = _reflection.GeneratedProtocolMessageType('rule_file_info', (_message.Message,), dict(
  DESCRIPTOR = _RULE_FILE_INFO,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.rule_file_info)
  ))
_sym_db.RegisterMessage(rule_file_info)

rule_file_chk = _reflection.GeneratedProtocolMessageType('rule_file_chk', (_message.Message,), dict(
  DESCRIPTOR = _RULE_FILE_CHK,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.rule_file_chk)
  ))
_sym_db.RegisterMessage(rule_file_chk)

rule_names = _reflection.GeneratedProtocolMessageType('rule_names', (_message.Message,), dict(
  DESCRIPTOR = _RULE_NAMES,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.rule_names)
  ))
_sym_db.RegisterMessage(rule_names)

fact_names = _reflection.GeneratedProtocolMessageType('fact_names', (_message.Message,), dict(
  DESCRIPTOR = _FACT_NAMES,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.fact_names)
  ))
_sym_db.RegisterMessage(fact_names)

fact_file_info = _reflection.GeneratedProtocolMessageType('fact_file_info', (_message.Message,), dict(
  DESCRIPTOR = _FACT_FILE_INFO,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.fact_file_info)
  ))
_sym_db.RegisterMessage(fact_file_info)

fact_file_chk = _reflection.GeneratedProtocolMessageType('fact_file_chk', (_message.Message,), dict(
  DESCRIPTOR = _FACT_FILE_CHK,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.fact_file_chk)
  ))
_sym_db.RegisterMessage(fact_file_chk)

fact_list = _reflection.GeneratedProtocolMessageType('fact_list', (_message.Message,), dict(
  DESCRIPTOR = _FACT_LIST,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.fact_list)
  ))
_sym_db.RegisterMessage(fact_list)

fact_var = _reflection.GeneratedProtocolMessageType('fact_var', (_message.Message,), dict(
  DESCRIPTOR = _FACT_VAR,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.fact_var)
  ))
_sym_db.RegisterMessage(fact_var)

mapper = _reflection.GeneratedProtocolMessageType('mapper', (_message.Message,), dict(
  DESCRIPTOR = _MAPPER,
  __module__ = 'file_pb2'
  # @@protoc_insertion_point(class_scope:buaa.file.mapper)
  ))
_sym_db.RegisterMessage(mapper)


# @@protoc_insertion_point(module_scope)
